project:
  type: website

website:
  title: "Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects/Experience
#      - href: test.qmd
#        text: Test
      - href: blogs.qmd
        text: Blog Posts
    right:
      - icon: github
        menu:
          - text: Website Source Code
            url: https://github.com/Jschnizzle/personal-website
  page-footer:
    right: "&copy; 2024, Jeremy Shiu"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
exectue:
  freeze: auto


